/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pl.tk.playground;

import pl.tk.playground.Expr.IntExpr;
import pl.tk.playground.Expr.StringExpr;

enum Invoice {
    SEND, PAID, OVERDUE
}

sealed interface Expr permits Expr.IntExpr, Expr.StringExpr {
    record IntExpr(int val) implements Expr {
    };

    record StringExpr(String val) implements Expr {
    };
}

public class App {


    public void RunThisCode(Expr exp) {
        var k = new Premium();
        
        if (exp instanceof IntExpr ie) {
            ie.val();
        } else if (exp instanceof StringExpr se) {

        } else {

        }
    }

    public String OnInvoice(Invoice i) {

        Object i1 = Invoice.SEND;

        if (i1 instanceof Invoice in) {

        }

        return switch (i) {
            case SEND -> "send";
            case PAID -> "paid";
            case OVERDUE -> "overdue";
        };

    }

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
